declare module '@adminjs/design-system' {
	export const Badge: any;
	export const Box: any;
	export const Button: any;
	export const CurrentUserNav: any;
	export const DropDown: any;
	export const DropDownItem: any;
	export const DropDownMenu: any;
	export const DropDownTrigger: any;
	export const FormGroup: any;
	export const H1: any;
	export const H2: any;
	export const H3: any;
	export const H4: any;
	export const H5: any;
	export const H6: any;
	export const Header: any;
	export const Icon: any;
	export const Illustration: any;
	export const Input: any;
	export const Label: any;
	export const MessageBox: any;
	export const Select: any;
	export const Text: any;
	export const cssClass: any;
}
